# 端口号
server:
  port: 12345

spring:
  # 服务名称
  application:
    name: springboot
  # redis配置
  redis:
    host: localhost
    port: 6379
    timeout: 6000ms  # 超时时间
    jedis:
      pool:
        # 连接池最大连接数
        max-active: 1000
        # 连接池最大阻塞等待时间
        max-wait: 2000ms
        # 连接池中最大空闲连接
        max-idle: 10
        # 连接池中最小空闲连接
        min-idle: 5
  # 数据库配置
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springboot
      username: root
      password: Jiang950813
      # 初始化时数据库物理连接的个数
      initial-size: 5
      # 最大连接池数量
      max-active: 30
      # 最小连接池数量
      min-idle: 5
      # 获取连接的最大等待时间
      max-wait: 30000
      # 检测并关闭控线连接的时间间隔
      time-between-eviction-runs-millis: 30000
      # 检测连接是否有效
      validation-query: SELECT 1 FROM DUAL
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500